In [1]:
import numpy as np

## Data Types

In [10]:
int_array=[1,2,3,4,5]
float_array=[1.0,2.1,3.2,4.0,5.2]

In [11]:
int_np=np.array(int_array)
int_np.dtype

dtype('int64')

In [12]:
float_np=np.array(float_array)
float_np.dtype

dtype('float64')

## Continuous Array

In [13]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [33]:
x[0:6]

array([0, 1, 2, 3, 4, 5])

In [34]:
x[0:6:2]

array([0, 2, 4])

## Random Array

In [79]:
x = np.random.randint(10,size=(10))
x

array([6, 4, 3, 4, 5, 8, 2, 5, 4, 1])

In [15]:
x = np.random.randint(100, size=(3, 4))
x

array([[75, 19, 59,  6],
       [91, 89,  6, 82],
       [81, 11, 73, 72]])

## Slicing

In [16]:
x[:3, ::2]

array([[75, 59],
       [91,  6],
       [81, 73]])

In [17]:
x.shape

(3, 4)

## Reshaping

In [18]:
x2=x.reshape(2,6)

In [19]:
x2.shape

(2, 6)

In [21]:
x2

array([[75, 19, 59,  6, 91, 89],
       [ 6, 82, 81, 11, 73, 72]])

## Concatenate

In [22]:
x1 = np.random.randint(100, size=(10))
x2 = np.random.randint(100, size=(10))
x1,x2

(array([70, 25, 47, 76, 59, 50, 39, 36, 31, 94]),
 array([64, 55, 22, 69, 92, 30, 56,  6, 55, 25]))

In [23]:
x=np.concatenate([x1,x2])
x

array([70, 25, 47, 76, 59, 50, 39, 36, 31, 94, 64, 55, 22, 69, 92, 30, 56,
        6, 55, 25])

## Splitting

In [89]:
x1, x2, x3 = np.split(x, [5, 8])
print(x1, x2, x3)

[77  2 90 90 90] [53 14 35] [54  9 78 75 40 13 83 89 28 67 28 52]


## Basic Statistics

In [28]:
x

array([70, 25, 47, 76, 59, 50, 39, 36, 31, 94, 64, 55, 22, 69, 92, 30, 56,
        6, 55, 25])

In [24]:
x.max()

94

In [25]:
x.argmax()

9

In [26]:
x[x.argmax()]

94

In [29]:
np.mean(x)

50.05

In [30]:
np.median(x)

52.5

In [31]:
np.std(x)

22.97493199119423

In [32]:
np.var(x)

527.8475000000001